version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    ports:
      - "10001:10001"   # HTTP
      - "10002:443"     # HTTPS
      - "10003:22"      # SSH
      - "80:80"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://3.36.103.119:10001' # Change this to your GitLab's URL
        gitlab_rails['initial_root_password'] = 'Blud1234567'
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    ports:
      - "8093:8093"   # HTTP
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner/config:/etc/gitlab-runner